/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PostsIndexRouteImport } from "./routes/posts/index"
import { Route as DefIndexRouteImport } from "./routes/def/index"
import { Route as AbcIndexRouteImport } from "./routes/abc/index"
import { Route as PostsPostIdRouteImport } from "./routes/posts/$postId"
import { Route as PostsCreateIndexRouteImport } from "./routes/posts/create/index"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: "/posts/",
  path: "/posts/",
  getParentRoute: () => rootRouteImport,
} as any)
const DefIndexRoute = DefIndexRouteImport.update({
  id: "/def/",
  path: "/def/",
  getParentRoute: () => rootRouteImport,
} as any)
const AbcIndexRoute = AbcIndexRouteImport.update({
  id: "/abc/",
  path: "/abc/",
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: "/posts/$postId",
  path: "/posts/$postId",
  getParentRoute: () => rootRouteImport,
} as any)
const PostsCreateIndexRoute = PostsCreateIndexRouteImport.update({
  id: "/posts/create/",
  path: "/posts/create/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/posts/$postId": typeof PostsPostIdRoute
  "/abc": typeof AbcIndexRoute
  "/def": typeof DefIndexRoute
  "/posts": typeof PostsIndexRoute
  "/posts/create": typeof PostsCreateIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/posts/$postId": typeof PostsPostIdRoute
  "/abc": typeof AbcIndexRoute
  "/def": typeof DefIndexRoute
  "/posts": typeof PostsIndexRoute
  "/posts/create": typeof PostsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/posts/$postId": typeof PostsPostIdRoute
  "/abc/": typeof AbcIndexRoute
  "/def/": typeof DefIndexRoute
  "/posts/": typeof PostsIndexRoute
  "/posts/create/": typeof PostsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/posts/$postId"
    | "/abc"
    | "/def"
    | "/posts"
    | "/posts/create"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/posts/$postId" | "/abc" | "/def" | "/posts" | "/posts/create"
  id:
    | "__root__"
    | "/"
    | "/posts/$postId"
    | "/abc/"
    | "/def/"
    | "/posts/"
    | "/posts/create/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  AbcIndexRoute: typeof AbcIndexRoute
  DefIndexRoute: typeof DefIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  PostsCreateIndexRoute: typeof PostsCreateIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/posts/": {
      id: "/posts/"
      path: "/posts"
      fullPath: "/posts"
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/def/": {
      id: "/def/"
      path: "/def"
      fullPath: "/def"
      preLoaderRoute: typeof DefIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/abc/": {
      id: "/abc/"
      path: "/abc"
      fullPath: "/abc"
      preLoaderRoute: typeof AbcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/posts/$postId": {
      id: "/posts/$postId"
      path: "/posts/$postId"
      fullPath: "/posts/$postId"
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/posts/create/": {
      id: "/posts/create/"
      path: "/posts/create"
      fullPath: "/posts/create"
      preLoaderRoute: typeof PostsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  AbcIndexRoute: AbcIndexRoute,
  DefIndexRoute: DefIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  PostsCreateIndexRoute: PostsCreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
